### ISSUE TITLE
When the psm monitor the node was down,Why the node status alway was show "Node alive or reachable"?

### ISSUE THREAD

**Issue by 150134230** [hashicorp/consul-esm#18] opened 2018-08-24 06:13 UTC
Is there any solution to this problem now?Thanks

![default](https://user-images.githubusercontent.com/40513089/44567671-1c89c200-a7a6-11e8-8ee9-8bf551cf1669.png)

**Comment by kyhavlov** [comment] 2018-08-31 08:34
It looks like there was a regression in 0.3.0 around node probes failing to update because of an invalid KV path (03f4fb0 should fix this). Can you try building from master and confirming that fixes the issue for you?

**Comment by kyhavlov** [comment] 2018-11-05 15:45
I'm going to close this out since this should be fixed as of 0.3.0. If anyone sees a similar issue on the latest version, feel free to open another issue with a description or comment here.

**Closed by kyhavlov** 2018-11-05 15:45 UTC
